### ISSUE TITLE
Change Helper Class Names

### ISSUE THREAD

**Issue by h-jennings** [h-jennings/code-perfect-mega-template#1]
Change helper class names to be more descriptive.

example:

```css
.paddBtm--xl {
padding-bottom: 40px; 
}
```

to:

```css
.paddBtm--40 {
padding-bottom: 40px; 
}
```

This will help with readability and development speed.
